spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onul?characterEncoding=UTF-8
    username: root
    password: zerone
  mvc:
    view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
     
server:
  port: 80    